In [1]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)

array = np.genfromtxt("taxi_tripdata.csv", delimiter=",", skip_header=1)
array.shape

(83691, 20)

In [2]:
TRIP_DISTANCE_COL_IDX=8

#Extrahiere die Spalte trip_distance und zeige die ersten 30 Einträge an.
array[:30,TRIP_DISTANCE_COL_IDX].shape

(30,)

In [3]:
#Extrahiere die Spalten fare_amount und tip_amount und zeige die ersten 30 Einträge an
FARE_AMOUNT_COL_IDX=9
TIP_AMOUNT_COL_IDX=12

array[:30,[FARE_AMOUNT_COL_IDX, TIP_AMOUNT_COL_IDX]].shape

(30, 2)

In [4]:
#Wähle gezielt einen Bereich aus: Zeilen 1011 bis 1097 und Spalten 6 bis 9.
array[1011:1098, 6:10].shape

(87, 4)

In [5]:
#Extrahiere jede zweite Zeile der Daten.
array[::2].shape

(41846, 20)

In [6]:
#Extrahiere die letzte Spalte des Arrays.
array[:,::2].shape

(83691, 10)

In [7]:
#Berechne den Durchschnitt der Spalte Trip_distance.
np.mean(array[:,TRIP_DISTANCE_COL_IDX])

194.35469931055908

In [8]:
#Ermittle den Median und die Standardabweichung der Spalte Fare_amount.
print(f"mean: {np.mean(array[:, FARE_AMOUNT_COL_IDX])}")
print(f"median: {np.median(array[:, FARE_AMOUNT_COL_IDX])}")
print(f"std: {np.std(array[:, FARE_AMOUNT_COL_IDX])}")

mean: 20.388304596671087
median: 16.0
std: 15.583459255873132


In [9]:
#Summiere die Werte der Spalte Total_amount.

TOTAL_AMOUNT_COL_IDX=16
array[:,TOTAL_AMOUNT_COL_IDX].sum()

2025726.9600000002

In [10]:
#Die Summe aller Spalten
array.sum(axis=0)

array([        nan,         nan,         nan,         nan,         nan,
        9068972.  , 11153500.  ,         nan, 16265739.14,  1706317.6 ,
          96805.95,    24568.5 ,    88596.81,    52267.45,         nan,
          24918.6 ,  2025726.96,         nan,         nan,         nan])

In [11]:
# wir filtern alle datensätze mit trip distance > 5 heraus
array[array[:,TRIP_DISTANCE_COL_IDX]>5].shape

(25756, 20)

In [14]:
# Wähle alle Zeilen aus, bei denen `passenger_count` genau **1** ist.  
PASSENGER_COUNT_COL_IDX=7
array[array[:,PASSENGER_COUNT_COL_IDX]==1].shape


(44127, 20)

In [17]:
#Ermittle Fahrten, bei denen `Fare_amount` zwischen **10 und 20 Dollar** liegt.
fare_amount_above_ten=array[:,FARE_AMOUNT_COL_IDX]>=10
array[fare_amount_above_ten & (array[:,FARE_AMOUNT_COL_IDX]<20)].shape


(26945, 20)

In [18]:
#Kombiniere Bedingungen: Fahrten mit mehr als **2 Passagieren** und einer Strecke unter **2 Meilen**.
array[(array[:,PASSENGER_COUNT_COL_IDX]>2) & (array[:,TRIP_DISTANCE_COL_IDX]<2)].shape


(1605, 20)

In [19]:
# Zähle Fahrten mit genau **0 Passagieren**.
array[array[:,PASSENGER_COUNT_COL_IDX]==0].shape

(56, 20)

In [24]:
# Berechne den **Fahrpreis pro Meile** für jede Fahrt.
# fare_amount/trip_distance

valid_mask = array[:, TRIP_DISTANCE_COL_IDX]>0
result=array[valid_mask, FARE_AMOUNT_COL_IDX]/array[valid_mask, TRIP_DISTANCE_COL_IDX]
result.shape

ValueError: operands could not be broadcast together with shapes (83691,) (80236,) 

In [25]:
# In den Daten hat sich ein Fehler eingeschlichen: Erhöhe alle `Fare_amount` um **10%**.
fare_amount=array[:, FARE_AMOUNT_COL_IDX]
print(fare_amount[:10])
fare_amount=fare_amount*1.1
print("preiserhöhung")
print(fare_amount[:10])

[ 6.  42.   6.5  6.5  7.   8.  17.5  5.   7.   7.5]
preiserhöhung
[ 6.6  46.2   7.15  7.15  7.7   8.8  19.25  5.5   7.7   8.25]


In [28]:
# Speichere ein gefiltertes Subset der Daten als **CSV-Datei**.

np.savetxt("test2.csv", array[array[:, TRIP_DISTANCE_COL_IDX]>0], delimiter=',')

(83691, 20)

20.388304596671087

array([[ 1.  , 56.  ,  0.5 ],
       [ 1.  , 31.  ,  0.5 ],
       [ 1.  , 19.5 ,  0.5 ],
       ...,
       [  nan, 20.93,  0.  ],
       [  nan, 19.16,  0.  ],
       [  nan, 22.45,  0.  ]])